# fly.toml app configuration file generated for phonebook-back-1 on 2023-12-18T17:15:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phonebook-back-1"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.ports]]
  handlers = ["http"]
  protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  protocol = "tls"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
